package:
  name: "pynsitu"
  version: "0.0.2"

source:
  git_url: https://github.com/apatlpo/pynsitu

build:
  number: 0

requirements:
  host:
    - python
    - setuptools
  build:
    - python {{ python }} 
  run:
    - python
    - numpy<=2.0 # imposed by numba
    - xarray
    - geopandas
    - cartopy
    - hvplot
    - geoviews
    - folium
    - cmocean
    - gsw
    - pytide
    - pip

about:
  home: https://github.com/apatlpo/pynsitu
  license: MIT
  license_familY: MIT
  license_file: LICENSE
  summary: "Various tools for the processing of oceanographic data based on pandas/xarray"

extra:
  recipe-maintainers:
    - apatlpo
