name: pynsitu
channels:
#  - pyviz
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - xarray
  - numpydoc
  - sphinx
  - ipython
  - jupyter
  - matplotlib
  - pandoc
  - pip
  - pip:
    - docrep
    - nbsphinx
    - sphinxcontrib-apidoc