name: pynsitu
channels:
#  - pyviz
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - xarray
  - zarr
#  - netcdf4
#  - geopandas
#  - hvplot
#  - seaborn
#  - cartopy
#  - geoviews
#  - folium
  - cmocean
#  - xrft
  - gsw
#  - pyinterp
#  - pytide
#  - pyTMD
  - numpydoc
  - sphinx
  - ipython
  - jupyter
  - matplotlib
  - pandoc
  - pip
  - pip:
#    - pynmea2
#    - geojsoncontour
    - docrep
    - nbsphinx
    - sphinxcontrib-apidoc