name: pynsitu
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - xarray
  - numpydoc
  - sphinx
  - ipython
  - jupyter
  - matplotlib
  - pandoc
  - pip
  - pip:
    - docrep
    - nbsphinx
    - sphinxcontrib-apidoc
    - pangeo-sphinx-book-theme
    - sphinx-copybutton
    - sphinxcontrib-srclinks
    - sphinx-panels