name: insitu
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy<=2.0
  - xarray
  - numpydoc
  - sphinx
  - ipython
  - jupyter
  - matplotlib
  - numba
  - pandoc
  - pip
  - pip:
    - docrep
    - nbsphinx
    - sphinxcontrib-apidoc
    - sphinx-book-theme
    #- pangeo-sphinx-book-theme
    - sphinx-copybutton
    - sphinxcontrib-srclinks
    - sphinx-panels
    - myst-nb