name: pynsitu_dev
channels:
  - pyviz
  - conda-forge
  - defaults
dependencies:
  - xarray
  - geopandas
  - hvplot
  - geoviews
  - cartopy
  - folium
  - cmocean
  - gsw
  - pytide
  - pytest
  - pytest-cov
  - pip
  - pip:
    - geojsoncontour
    - codecov
    - pytest-xdist
    - black
