name: pynsitu
channels:
  - pyviz
  - conda-forge
  - defaults
dependencies:
  - xarray
  - zarr
  - netcdf4
  - geopandas
  - hvplot
  - geoviews
  - seaborn
  - cartopy
  - geoviews
  - folium
  - cmocean
  - xrft
  - gsw
  - pyinterp
  - pytide
  - pyTMD
  - pip
  - pip:
    - pynmea2
    - geojsoncontour
