name: pynsitu
channels:
  - pyviz
  - conda-forge
  - defaults
dependencies:
  - xarray
  - geopandas
  - cartopy
  - hvplot
  - geoviews
  - folium
  - cmocean
  - gsw
  - pytide
  - pip
  - pip:
    - geojsoncontour
