name: insitu
channels:
  - pyviz
  - conda-forge
  - defaults
dependencies:
  - numpy<=2.0 # imposed by numba
  - xarray
  - geopandas
  - cartopy
  - hvplot
  - geoviews
  - folium
  - cmocean
  - gsw
  - pytide
#  - pyTMD
#  - utide
  - pip
